/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiFeedbackPanel: typeof import('./src/components/exam/result/AiFeedbackPanel.vue')['default']
    AnswerReviewSection: typeof import('./src/components/exam/result/AnswerReviewSection.vue')['default']
    AudioStatusBanner: typeof import('./src/components/exam/stages/AudioStatusBanner.vue')['default']
    AuthLayout: typeof import('./src/components/layout/AuthLayout.vue')['default']
    BackTopButton: typeof import('./src/components/layout/BackTopButton.vue')['default']
    BlankFillingBlock: typeof import('./src/components/exam/stages/BlankFillingBlock.vue')['default']
    ChoiceBlock: typeof import('./src/components/exam/stages/ChoiceBlock.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ExamFooter: typeof import('./src/components/exam/ExamFooter.vue')['default']
    ExamHeader: typeof import('./src/components/exam/ExamHeader.vue')['default']
    ExamSessionCard: typeof import('./src/components/exam/stages/ExamSessionCard.vue')['default']
    ListeningStage: typeof import('./src/components/exam/stages/ListeningStage.vue')['default']
    MatchingBlock: typeof import('./src/components/exam/stages/MatchingBlock.vue')['default']
    PageTopBar: typeof import('./src/components/layout/PageTopBar.vue')['default']
    QuestionOptionList: typeof import('./src/components/exam/stages/QuestionOptionList.vue')['default']
    ReadingStage: typeof import('./src/components/exam/stages/ReadingStage.vue')['default']
    ResultOverview: typeof import('./src/components/exam/result/ResultOverview.vue')['default']
    ResultPageHeader: typeof import('./src/components/layout/ResultPageHeader.vue')['default']
    ResultSkeleton: typeof import('./src/components/exam/result/ResultSkeleton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillBreakdown: typeof import('./src/components/exam/result/SkillBreakdown.vue')['default']
    TextAnswerQuestion: typeof import('./src/components/exam/stages/TextAnswerQuestion.vue')['default']
    TranslationStage: typeof import('./src/components/exam/stages/TranslationStage.vue')['default']
    WritingStage: typeof import('./src/components/exam/stages/WritingStage.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
